language: java

os:
    - linux

jdk:
    - openjdk8

services:
    - redis

install:
    - mvn clean
    - mvn checkstyle:check
    - mvn compile

script:
    - mvn package

after_success:
    - bash <(curl -s https://codecov.io/bash)
